// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6RmPw2DTl3fEpSg7YK-UZ84X8pspLpo',
    appId: '1:839689695356:web:2b697b0da044a9750a99f9',
    messagingSenderId: '839689695356',
    projectId: 'smartstudentapp-5ecc6',
    authDomain: 'smartstudentapp-5ecc6.firebaseapp.com',
    storageBucket: 'smartstudentapp-5ecc6.firebasestorage.app',
    measurementId: 'G-G9W2M7GLPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBEtpxu1q-fqK43EkSBdn1SKJ_iXUUDxU',
    appId: '1:839689695356:android:ae53bdf681a715610a99f9',
    messagingSenderId: '839689695356',
    projectId: 'smartstudentapp-5ecc6',
    storageBucket: 'smartstudentapp-5ecc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcAYbR0mwpefAsM4_bZhBIeLuN_cFJ_ao',
    appId: '1:839689695356:ios:863d10383dc83da80a99f9',
    messagingSenderId: '839689695356',
    projectId: 'smartstudentapp-5ecc6',
    storageBucket: 'smartstudentapp-5ecc6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcAYbR0mwpefAsM4_bZhBIeLuN_cFJ_ao',
    appId: '1:839689695356:ios:863d10383dc83da80a99f9',
    messagingSenderId: '839689695356',
    projectId: 'smartstudentapp-5ecc6',
    storageBucket: 'smartstudentapp-5ecc6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-6RmPw2DTl3fEpSg7YK-UZ84X8pspLpo',
    appId: '1:839689695356:web:25f3e3c6bff192ba0a99f9',
    messagingSenderId: '839689695356',
    projectId: 'smartstudentapp-5ecc6',
    authDomain: 'smartstudentapp-5ecc6.firebaseapp.com',
    storageBucket: 'smartstudentapp-5ecc6.firebasestorage.app',
    measurementId: 'G-LVP0X7MD0F',
  );
}
